### ISSUE TITLE
undefined method `offset'

### ISSUE THREAD

**Issue by radist** [noshutdown-ru/vault#23]
После обновления на последнюю версию

```
I, [2018-02-10T22:43:07.092208 #22464]  INFO -- : Completed 500 Internal Server Error in 82ms (ActiveRecord: 18.1ms)
F, [2018-02-10T22:43:07.094158 #22464] FATAL -- : 
NoMethodError (undefined method `offset' for #<Array:0x007f9e5c152c30>):
  plugins/vault/app/controllers/keys_controller.rb:60:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by noshutdown-ru-user** [comment]
Спасибо что сообщили в ближайшее время постараемся исправить, пока можете откатиться на предыдущую версию, это не затронет изменений в базе.

**Comment by jmtemmos** [comment]
Same error for me.
Redmine 3.4.2.stable.16947
0.3.5

**Comment by noshutdown-ru-user** [comment]
https://github.com/noshutdown-ru/vault/releases/tag/release_0.3.6
