### ISSUE TITLE
Save keys 500 error

### ISSUE THREAD

**Issue by Salivaxiu** [noshutdown-ru/vault#38]
![image](https://user-images.githubusercontent.com/2322026/40485592-9394b880-5f91-11e8-81b1-c44f4177a345.png)

Other fields can be saved

i cant save key fields

```
Started POST "/projects/test/keys" for 111.199.175.11 at 2018-05-24 20:28:36 +0800
Processing by KeysController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"9963/JYHnuhiM6+kIlLqXLmYaZ85UU1B+tauCtTOravRJHCkdXSN5BPjeYNhfqWe0e3qZCKrPxuoNXec+3CadQ==", "vault_key"=>{"name"=>"1", "login"=>"2", "url"=>"3", "type"=>"Vault::Password", "body"=>"1234567890", "tags"=>"", "comment"=>""}, "commit"=>"保存", "project_id"=>"test"}
  Current user: admin (id=1)
WARNING: Can't mass-assign protected attributes for Vault::Password: tags
	plugins/vault/app/controllers/keys_controller.rb:80:in `create'
	lib/redmine/sudo_mode.rb:63:in `sudo_mode'
	plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'
Completed 500 Internal Server Error in 49ms (ActiveRecord: 18.0ms)

OpenSSL::Cipher::CipherError (key length too short):
  plugins/vault/lib/vault_cipher.rb:9:in `key='
  plugins/vault/lib/vault_cipher.rb:9:in `encrypt_text'
  plugins/vault/lib/encryptor.rb:6:in `encrypt'
  plugins/vault/app/models/vault/password.rb:8:in `encrypt!'
  plugins/vault/app/controllers/keys_controller.rb:88:in `block in create'
  plugins/vault/app/controllers/keys_controller.rb:87:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'
```

```
Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
```

**Comment by noshutdown-ru-user** [comment]
key length too short
you need to change encryption key
minimum 32 simbols RyRovryaDruojyownoapVarcuvbudigs

**Comment by noshutdown-ru-user** [comment]
we will add validation for this

**Comment by Salivaxiu** [comment]
OMG~ hahaha

Thank for you help 

I like the plugins
