### ISSUE TITLE
Backup NoMethodError (undefined method `file'

### ISSUE THREAD

**Issue by redfox1993** [noshutdown-ru/vault#60]
Hi there,

Your plugin is great so far, but I got an error when I want to create a backup.
I am using Redmine 4.1

```
Started POST "/vault_settings/backup" for 192.168.50.179 at 2020-01-30 16:19:08 +0000
Processing by VaultSettingsController#backup as HTML
  Parameters: {"authenticity_token"=>"BXrm/ECyiienrnghuc4w7HPyw/nGNfCft/QIP/Eap22DFR99+gzOkeibptcVB4VZVTfGX8FPUaBRrQGnpAhJEA=="}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 28ms (ActiveRecord: 9.0ms)

NoMethodError (undefined method `file' for #<Zip::File:0x00007f7479682aa0>):

plugins/vault/app/controllers/vault_settings_controller.rb:55:in `block in backup'
plugins/vault/app/controllers/vault_settings_controller.rb:54:in `backup'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
```

What can I do?
kind regards
Red

**Comment by noshutdown-ru-user** [comment]
Thx for report, will take a look this weekends

**Comment by noshutdown-ru-user** [comment]
This problem can be related to other plugin which is using gem `zip`.
Gem `zip` and `rubyzip` have same names for modules.
Can you check Gemfiles of plugins is any of them using `zip` ?

**Comment by redfox1993** [comment]
Sorry i dont understand. I am at the beginning to understand ruby.   
The error comes up, when I was trying to backup the vault.

I dont think that my other installed plugins used zip but If so, is it not possible to make using the right module in your plugin?

**Comment by noshutdown-ru-user** [comment]
Can you try this branch https://github.com/noshutdown-ru/vault/tree/development

**Comment by noshutdown-ru-user** [comment]
> Sorry i dont understand. I am at the beginning to understand ruby.
> The error comes up, when I was trying to backup the vault.
> 
> I dont think that my other installed plugins used zip but If so, is it not possible to make using the right module in your plugin?

Can you provide list of installed plugins ?

**Comment by redfox1993** [comment]
I have changed the branch to development and pulled it. 

> Fast-forward
 .travis.yml | 2 +-
 Gemfile     | 3 +++
 2 files changed, 4 insertions(+), 1 deletion(-)

then bundle install.

Now I was not able to call my Redmine application.
I couldn't find any error logs, so I have pulled the master branch

the other plugin that uses rubyzip is the dmsf plugin.
(maybe? https://github.com/danmunn/redmine_dmsf/pull/110)

**Comment by noshutdown-ru-user** [comment]
Can you remove this plugin and try with master branch of vault ?
Also can you comment this strings in hist plugin https://github.com/danmunn/redmine_dmsf/blob/master/Gemfile#L23-L24 and try our master branch ?

**Comment by redfox1993** [comment]
I 've commented the lines but it doesn't work, though. I'm afraid that removing the DMSF Plugin is not an option, cause of WebDAV, documents, full text, etc :(

**Comment by noshutdown-ru-user** [comment]
We will try to check is it connected to this plugin https://github.com/danmunn/redmine_dmsf or something else.

**Comment by redfox1993** [comment]
Hi there,
Any progress?

**Comment by noshutdown-ru-user** [comment]
not yet, sorry

**Comment by noshutdown-ru-user** [comment]
with old version all work ?

**Comment by redfox1993** [comment]
with the old version, I can start my Redmine site. The Development branch causes a crash of my Redmine.

**Comment by noshutdown-ru-user** [comment]
ok pls don't use now Development
