### ISSUE TITLE
Incompatibility problem

### ISSUE THREAD

**Issue by ccolussi** [noshutdown-ru/vault#85]
In our environment, we use redmine 4.1.4 and following plugins:
Redmine Agile plugin (PRO version) - RedmineUP 1.6.2
Redmine Checklists plugin (PRO version) - RedmineUP 3.1.19
Redmine Drive plugin (PRO version) - RedmineUP 1.1.1
Redmine Favorite Projects plugin - RedmineUP 2.1.1
Redmine People plugin (PRO version) - RedmineUP 1.6.1	
Redmine Q&A plugin (PRO version) - RedmineUP 1.0.2
Redmine Reporter plugin (PRO version) - RedmineUP 2.0.0
Redmine Resources plugin (PRO version) - RedmineUP 1.0.5
Risks - eXolnet	1.4.1	
Redmine Tags plugin (Light version) - RedmineUP 2.0.11

So, after installing vault plugin, Risks plugin stops working.

Error log:
Started GET "/projects/keyworks/risks/new" for 192.168.1.58 at 2021-09-21 11:05:53 -0300
Processing by RisksController#new as HTML
  Parameters: {"project_id"=>"new_project"}
  Current user: john.doe (id=5)
Completed 500 Internal Server Error in 57ms (ActiveRecord: 40.1ms)
  
ArgumentError (wrong number of arguments (given 2, expected 0..1)):
  
plugins/redmine_risks/app/controllers/risks_controller.rb:205:in `build_new_risk_from_params'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

Could you help?

**Comment by rafaelios** [comment]
This incompatibility seems to be related to the gem 'protected_attributes_continued' when state_machines is used inside a model that extends ActiveRecord::Base. As a workaround, i removed this gem and made some tweaks, but this change might break in older versions of redmine.

**Comment by JKeySZR** [comment]
a similar problem when using the commercial module  redmine-automation
(_https://alphanodes.com/redmine-automation_)
vault  breaks module logic redmine-automation and redmine get 

ArgumentError (wrong number of arguments (given 2, expected 0..1)):
